# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "05bcc0b4784c5196df9b274d67c57496"
name = "Ab Testing"
application_url = "https://remarkable-butterfly-looksmart-louise.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-07"
  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_themes,read_orders"

[auth]
redirect_urls = [
  "https://remarkable-butterfly-looksmart-louise.trycloudflare.com/api/auth"
]