import { useState, useCallback, useMemo } from "react";
import {
    Card,
    Text,
    Button,
    InlineStack,
    BlockStack,
    Box,
    Badge,
    Icon,
    Checkbox,
    TextField,
    Tabs,
} from "@shopify/polaris";
import { StarFilledIcon, SearchIcon, XIcon } from "@shopify/polaris-icons";

const METRIC_GROUPS = [
    {
        id: "conversion",
        label: "Conversion Metrics",
        metrics: [
            { id: "conversion_rate", label: "Conversion Rate", description: "Orders divided by unique visitors" },
            { id: "add_to_cart_rate", label: "Add to Cart Rate", description: "Percentage of visitors who added a product to cart" },
            { id: "abandoned_cart_rate", label: "Abandoned Cart Rate", description: "Percentage of visitors who added to cart but did not make an order" },
            { id: "checkout_begin_rate", label: "Checkout - begin rate", description: "Percentage of visitors who started checkout" },
            { id: "checkout_contact_info_rate", label: "Checkout - enter contact info rate", description: "Percentage of visitors who entered contact information (email or phone number) at checkout" },
            { id: "checkout_address_rate", label: "Checkout - enter address rate", description: "Percentage of visitors who entered their shipping address and saw shipping rates at checkout" },
            { id: "abandoned_checkout_rate", label: "Abandoned Checkout Rate", description: "Percentage of visitors who started checkout but did not make an order" },
            { id: "view_product_page_rate", label: "View product page rate", description: "Percent of unique site visitors who viewed a product page" },
            { id: "view_collection_page_rate", label: "View Collection Page Rate", description: "Percentage of visitors who viewed a collection page" },
        ],
    },
    {
        id: "revenue",
        label: "Revenue Metrics",
        metrics: [
            { id: "revenue_per_visitor", label: "Revenue per Visitor", description: "Net revenue divided by number of unique visitors. Net revenue includes product and shipping revenue, net of discounts" },
            { id: "average_order_value", label: "Average Order Value", description: "Net revenue divided by number of orders (also known as average order value, AOV)" },
            { id: "avg_units_per_order", label: "Avg units per order", description: "Total unit quantity divided by number of orders" },
            { id: "avg_product_revenue_per_unit", label: "Avg product revenue per unit", description: "Net product revenue divided by unit quantity (i.e., average net price paid per unit)" },
        ],
    },
    {
        id: "profit",
        label: "Profit Metrics",
        metrics: [
            { id: "profit_per_visitor", label: "Profit per Visitor", description: "Gross profit (net revenue - COGS, cost of shipping, and transaction fees) divided by number of unique visitors" },
            { id: "profit_per_order", label: "Profit per Order", description: "Gross profit divided by number of orders" },
        ],
    },
    {
        id: "shipping",
        label: "Shipping Metrics",
        metrics: [
            { id: "free_shipping_pct", label: "% Orders with Free Shipping", description: "Percentage of orders with no associated net shipping revenue" },
            { id: "net_shipping_revenue_per_order", label: "Net Shipping Revenue per Order", description: "Average net revenue per order generated by shipping charges. This is the shipping revenue portion of AOV." },
        ],
    },
    {
        id: "subscription",
        label: "Subscription Metrics",
        metrics: [
            { id: "sub_orders_per_visitor", label: "Subscription orders per visitor", description: "Number of new subscription orders divided by number of unique visitors" },
            { id: "sub_revenue_per_visitor", label: "Subscription revenue per visitor", description: "Net revenue from new subscription orders divided by number of unique visitors" },
            { id: "sub_profit_per_visitor", label: "Subscription profit per visitor", description: "Gross profit from new subscription orders divided by number of unique visitors" },
            { id: "sub_order_aov", label: "Subscription order AOV", description: "Average net revenue per new subscription order" },
            { id: "sub_pct_of_orders", label: "Subscription % of orders", description: "Percentage of orders that contained a subscription" },
        ],
    },
    {
        id: "discount",
        label: "Discount Metrics",
        metrics: [
            { id: "avg_discount_all_orders", label: "Avg discount per all orders (i.e., GTN $)", description: "Average discount per order, including 0s from orders with no discount" },
            { id: "avg_discount_discounted_order", label: "Avg discount per discounted order", description: "Average discount per order with a discount applied" },
        ],
    },
];

const ALL_METRICS = METRIC_GROUPS.flatMap((g) => g.metrics);
const getMetric = (id) => ALL_METRICS.find((m) => m.id === id);

const DEFAULT_SELECTED_IDS = [
    "conversion_rate",
    "revenue_per_visitor",
    "profit_per_visitor",
    "average_order_value",
];
const DEFAULT_PRIMARY_ID = "conversion_rate";
const MAX_SELECTED = 7;

export default function ConfigureAnalytics() {
    const [selectedIds, setSelectedIds] = useState(DEFAULT_SELECTED_IDS);
    const [primaryId, setPrimaryId] = useState(DEFAULT_PRIMARY_ID);

    const [drawerOpen, setDrawerOpen] = useState(false);
    const [draftSelectedIds, setDraftSelectedIds] = useState(DEFAULT_SELECTED_IDS);
    const [search, setSearch] = useState("");
    const [tab, setTab] = useState(0);

    const openDrawer = useCallback(() => {
        setDraftSelectedIds(selectedIds);
        setSearch("");
        setDrawerOpen(true);
    }, [selectedIds]);

    const closeDrawer = useCallback(() => setDrawerOpen(false), []);

    const handleSetPrimary = useCallback((id) => setPrimaryId(id), []);

    const handleRemove = useCallback(
        (id) => {
            setSelectedIds((prev) => {
                const next = prev.filter((m) => m !== id);
                if (primaryId === id) setPrimaryId(next[0] ?? null);
                return next;
            });
        },
        [primaryId]
    );

    const toggleDraft = useCallback((id) => {
        setDraftSelectedIds((prev) => {
            const isSelected = prev.includes(id);
            if (!isSelected && prev.length >= MAX_SELECTED) return prev; 
            return isSelected ? prev.filter((m) => m !== id) : [...prev, id];
        });
    }, []);

    const handleSave = useCallback(() => {
        setSelectedIds(draftSelectedIds);
        if (!draftSelectedIds.includes(primaryId)) {
            setPrimaryId(draftSelectedIds[0] ?? null);
        }
        setDrawerOpen(false);
    }, [draftSelectedIds, primaryId]);

    const filteredGroups = useMemo(() => {
        if (!search.trim()) return METRIC_GROUPS;
        const q = search.toLowerCase();
        return METRIC_GROUPS.map((g) => ({
            ...g,
            metrics: g.metrics.filter(
                (m) =>
                    m.label.toLowerCase().includes(q) ||
                    m.description.toLowerCase().includes(q)
            ),
        })).filter((g) => g.metrics.length > 0);
    }, [search]);

    const selectedMetrics = selectedIds.map(getMetric).filter(Boolean);
    const atLimit = draftSelectedIds.length >= MAX_SELECTED;

    return (
        <>
            <Card>
                <BlockStack gap="400">
                    <BlockStack gap="100">
                        <Text variant="headingMd" as="h2">
                            Choose your Key Metrics and Primary Metric
                        </Text>
                        <Text as="span" tone="subdued">
                            Choose up to {MAX_SELECTED} Key Metrics to appear on the front page of your test results.
                        </Text>
                    </BlockStack>

                    <BlockStack gap="200">
                        {/* Always-on default row */}
                        <Box
                            padding="400"
                            borderWidth="025"
                            borderColor="border"
                            borderRadius="200"
                        >
                            <InlineStack gap="200" blockAlign="start" wrap={false}>
                                <Box paddingBlockStart="050">
                                    <Text as="span" tone="success">✓</Text>
                                </Box>
                                <BlockStack gap="050">
                                    <Text as="span" fontWeight="semibold">
                                        Visitors, Orders & Revenue
                                    </Text>
                                    <Text as="span" tone="subdued">
                                        These metrics are shown by default in every test
                                    </Text>
                                </BlockStack>
                            </InlineStack>
                        </Box>

                        {selectedMetrics.map((metric) => (
                            <Box
                                key={metric.id}
                                padding="400"
                                borderWidth="025"
                                borderColor="border"
                                borderRadius="200"
                            >
                                <InlineStack align="space-between" blockAlign="start" wrap={false}>
                                    <BlockStack gap="050">
                                        <Text as="span" fontWeight="semibold">
                                            {metric.label}
                                        </Text>
                                        <Text as="span" tone="subdued">
                                            {metric.description}
                                        </Text>
                                    </BlockStack>

                                    <InlineStack gap="200" blockAlign="center">
                                        {primaryId === metric.id ? (
                                            <InlineStack gap="100" blockAlign="center">
                                                <Icon source={StarFilledIcon} tone="magic" />
                                                <Badge tone="magic">Primary</Badge>
                                            </InlineStack>
                                        ) : (
                                            <Button
                                                variant="plain"
                                                onClick={() => handleSetPrimary(metric.id)}
                                            >
                                                Set as primary
                                            </Button>
                                        )}
                                        <Button
                                            variant="plain"
                                            tone="critical"
                                            onClick={() => handleRemove(metric.id)}
                                        >
                                            Remove
                                        </Button>
                                    </InlineStack>
                                </InlineStack>
                            </Box>
                        ))}
                    </BlockStack>

                    <InlineStack>
                        <Button onClick={openDrawer} icon={undefined}>
                            + Add Key Metric
                        </Button>
                    </InlineStack>
                </BlockStack>
            </Card>

            {drawerOpen && (
                <div
                    style={{
                        position: "fixed",
                        inset: 0,
                        zIndex: 512,
                        background: "rgba(0,0,0,0.35)",
                        display: "flex",
                        justifyContent: "flex-end",
                    }}
                    onClick={closeDrawer}
                >
                    <div
                        style={{
                            width: "480px",
                            maxWidth: "100%",
                            height: "100%",
                            background: "var(--p-color-bg-surface)",
                            display: "flex",
                            flexDirection: "column",
                            boxShadow: "var(--p-shadow-400)",
                        }}
                        onClick={(e) => e.stopPropagation()}
                    >
                        {/* Header */}
                        <Box padding="400" borderBlockEndWidth="025" borderColor="border">
                            <InlineStack align="space-between" blockAlign="center">
                                <Text variant="headingMd" as="h2">
                                    Select Key Metrics
                                </Text>
                                <Button variant="plain" icon={XIcon} onClick={closeDrawer} accessibilityLabel="Close" />
                            </InlineStack>
                            <Box paddingBlockStart="300">
                                <TextField
                                    labelHidden
                                    label="Search for metric"
                                    placeholder="Search for metric"
                                    value={search}
                                    onChange={setSearch}
                                    prefix={<Icon source={SearchIcon} />}
                                    autoComplete="off"
                                />
                            </Box>
                        </Box>

                        {/* Tabs */}
                        <Box paddingInline="400" paddingBlockStart="200">
                            <Tabs
                                tabs={[
                                    { id: "standard", content: `Standard Metrics` },
                                    { id: "custom", content: "Custom Metrics" },
                                ]}
                                selected={tab}
                                onSelect={setTab}
                            />
                        </Box>

                        {/* Body */}
                        <div style={{ flex: 1, overflowY: "auto", padding: "16px" }}>
                            {tab === 0 ? (
                                <BlockStack gap="400">
                                    {filteredGroups.map((group) => {
                                        const selectedInGroup = group.metrics.filter((m) =>
                                            draftSelectedIds.includes(m.id)
                                        ).length;
                                        return (
                                            <Box
                                                key={group.id}
                                                borderWidth="025"
                                                borderColor="border"
                                                borderRadius="200"
                                            >
                                                <Box
                                                    padding="300"
                                                    borderBlockEndWidth="025"
                                                    borderColor="border-secondary"
                                                >
                                                    <InlineStack gap="200" blockAlign="center">
                                                        <Text as="span" fontWeight="semibold" tone="subdued">
                                                            {group.label.toUpperCase()}
                                                        </Text>
                                                        {selectedInGroup > 0 && (
                                                            <Badge>{String(selectedInGroup)}</Badge>
                                                        )}
                                                    </InlineStack>
                                                </Box>
                                                <BlockStack gap="0">
                                                    {group.metrics.map((metric) => {
                                                        const checked = draftSelectedIds.includes(metric.id);
                                                        const disabled = !checked && atLimit;
                                                        return (
                                                            <Box
                                                                key={metric.id}
                                                                padding="300"
                                                                borderBlockEndWidth="025"
                                                                borderColor="border-secondary"
                                                            >
                                                                <div style={{ opacity: disabled ? 0.5 : 1 }}>
                                                                    <Checkbox
                                                                        label={
                                                                            <BlockStack gap="025">
                                                                                <Text as="span" fontWeight="medium">
                                                                                    {metric.label}
                                                                                </Text>
                                                                                <Text as="span" tone="subdued">
                                                                                    {metric.description}
                                                                                </Text>
                                                                            </BlockStack>
                                                                        }
                                                                        checked={checked}
                                                                        disabled={disabled}
                                                                        onChange={() => toggleDraft(metric.id)}
                                                                    />
                                                                </div>
                                                            </Box>
                                                        );
                                                    })}
                                                </BlockStack>
                                            </Box>
                                        );
                                    })}
                                    {filteredGroups.length === 0 && (
                                        <Text as="span" tone="subdued">
                                            No metrics match "{search}"
                                        </Text>
                                    )}
                                </BlockStack>
                            ) : (
                                <Text as="span" tone="subdued">
                                    No custom metrics yet.
                                </Text>
                            )}
                        </div>

                        {/* Footer */}
                        <Box padding="400" borderBlockStartWidth="025" borderColor="border">
                            <InlineStack align="space-between" blockAlign="center">
                                <Text as="span" tone="subdued">
                                    {draftSelectedIds.length}/{MAX_SELECTED} selected
                                </Text>
                                <InlineStack gap="200">
                                    <Button onClick={closeDrawer}>Cancel</Button>
                                    <Button variant="primary" onClick={handleSave}>
                                        Save Key Metrics
                                    </Button>
                                </InlineStack>
                            </InlineStack>
                        </Box>
                    </div>
                </div>
            )}
        </>
    );
}